import { Injectable } from '@angular/core';

const IMAGES = [
  // Heute
  {id: 1, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a1.jpg'},
  {id: 3, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a3.jpg'},
  {id: 4, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a4.jpg'},
  {id: 5, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a5.jpg'},
  {id: 6, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a6.jpg'},
  {id: 9, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a9.jpg'},
  {id: 10, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a10.jpg'},
  {id: 12, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a12.jpg'},
  {id: 13, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a13.jpg'},
  {id: 14, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a14.jpg'},
  {id: 15, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a15.jpg'},
  {id: 16, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a16.jpg'},
  {id: 17, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a17.jpg'},
  {id: 18, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a18.jpg'},
  {id: 19, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a19.jpg'},
  {id: 21, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a21.jpg'},
  {id: 2, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a2.jpg'},
  {id: 7, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a7.jpg'},
  {id: 8, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a8.jpg'},
  {id: 11, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a11.jpg'},
  {id: 20, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a20.jpg'},
  {id: 22, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a22.jpg'},
  {id: 23, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a23.jpg'},
  {id: 24, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a24.jpg'},
  {id: 25, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a25.jpg'},
  {id: 26, category: 'heute', caption: 'Büro Neustadt Bremen Nov. 2019', url: 'assets/my_images/a26.jpg'},
  {id: 27, category: 'heute', caption: 'Büro Neustadt Bremen Nov. 2019', url: 'assets/my_images/a27.jpg'},
  {id: 28, category: 'heute', caption: 'Büro Neustadt Bremen Nov. 2019', url: 'assets/my_images/a28.jpg'},
  {id: 29, category: 'heute', caption: 'Büro Neustadt Bremen Nov. 2019', url: 'assets/my_images/a29.jpg'},
  {id: 30, category: 'heute', caption: 'Büro Neustadt Bremen Nov. 2019', url: 'assets/my_images/a30.jpg'},
  {id: 31, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a31.jpg'},
  {id: 32, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a32.jpg'},
  {id: 33, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a33.jpg'},
  {id: 34, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a34.jpg'},
  {id: 35, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a35.jpg'},
  {id: 36, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a36.jpg'},
  {id: 37, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a37.jpg'},
  {id: 38, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a38.jpg'},
  {id: 39, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a39.jpg'},
  {id: 40, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a40.jpg'},
  {id: 41, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a41.jpg'},
  {id: 42, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a42.jpg'},
  {id: 43, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a43.jpg'},
  {id: 44, category: 'heute', caption: 'Neustadt Bremen Nov. 2019', url: 'assets/my_images/a44.jpg'},
  {id: 45, category: 'heute', caption: 'Nov. 2019', url: 'assets/my_images/a45.jpg'},
  {id: 46, category: 'heute', caption: 'Nov. 2019', url: 'assets/my_images/a46.jpg'},
  {id: 47, category: 'heute', caption: 'Nov. 2019', url: 'assets/my_images/a47.jpg'},
  {id: 48, category: 'heute', caption: 'Nov. 2019', url: 'assets/my_images/a48.jpg'},

  // Marathon Berlin
  {id: 49, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b1.jpg'},
  {id: 50, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b2.jpg'},
  {id: 51, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b3.jpg'},
  {id: 52, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b4.jpg'},
  {id: 53, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b5.jpg'},
  {id: 54, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b6.jpg'},
  {id: 55, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b66.jpg'},
  {id: 56, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b7.jpg'},
  {id: 57, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b8.jpg'},
  {id: 58, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b9.jpg'},
  {id: 59, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b10.jpg'},
  {id: 60, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b11.jpg'},
  {id: 61, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b12.jpg'},
  {id: 62, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b13.jpg'},
  {id: 63, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b14.jpg'},
  {id: 64, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b15.jpg'},
  {id: 65, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b16.jpg'},
  {id: 66, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b17.jpg'},
  {id: 67, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b18.jpg'},
  {id: 68, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b19.jpg'},
  {id: 69, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b20.jpg'},
  {id: 70, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b21.jpg'},
  {id: 71, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b22.jpg'},
  {id: 72, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b23.jpg'},
  {id: 73, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b24.jpg'},
  {id: 74, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b25.jpg'},
  {id: 75, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b26.jpg'},
  {id: 76, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b27.jpg'},
  {id: 77, category: 'berlin', caption: 'Berlin Sept. 2014', url: 'assets/my_images/b28.jpg'},

  // köln
  {id: 78, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c1.jpg'},
  {id: 79, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c2.jpg'},
  {id: 80, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c3.jpg'},
  {id: 81, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c4.jpg'},
  {id: 82, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c5.jpg'},
  {id: 83, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c6.jpg'},
  {id: 84, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c7.jpg'},
  {id: 85, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c8.jpg'},
  {id: 86, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c9.jpg'},
  {id: 87, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c10.jpg'},
  {id: 88, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c11.jpg'},
  {id: 89, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c12.jpg'},
  {id: 90, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c13.jpg'},
  {id: 91, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c14.jpg'},
  {id: 92, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c15.jpg'},
  {id: 93, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c16.jpg'},
  {id: 94, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c17.jpg'},
  {id: 95, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c18.jpg'},
  {id: 96, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c19.jpg'},
  {id: 97, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c20.jpg'},
  {id: 98, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c21.jpg'},
  {id: 99, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c22.jpg'},
  {id: 100, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c23.jpg'},
  {id: 101, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c24.jpg'},
  {id: 102, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c25.jpg'},
  {id: 103, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c26.jpg'},
  {id: 104, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c27.jpg'},
  {id: 105, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c28.jpg'},
  {id: 106, category: 'köln', caption: 'Köln Aug. 2014', url: 'assets/my_images/c29.jpg'},

  // frankfurt
  {id: 107, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d1.jpg'},
  {id: 108, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d2.jpg'},
  {id: 109, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d3.jpg'},
  {id: 110, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d4.jpg'},
  {id: 111, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d5.jpg'},
  {id: 112, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d6.jpg'},
  {id: 113, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d7.jpg'},
  {id: 114, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d8.jpg'},
  {id: 115, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d9.jpg'},
  {id: 116, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d10.jpg'},
  {id: 117, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d11.jpg'},
  {id: 118, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d12.jpg'},
  {id: 119, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d13.jpg'},
  {id: 120, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d14.jpg'},
  {id: 121, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d15.jpg'},
  {id: 122, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d16.jpg'},
  {id: 123, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d17.jpg'},
  {id: 124, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d18.jpg'},
  {id: 125, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d19.jpg'},
  {id: 126, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d20.jpg'},
  {id: 127, category: 'frankfurt', caption: 'Frankfurt Okt. 2012', url: 'assets/my_images/d21.jpg'},

  {id: 128, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e1.jpg'},
  {id: 129, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e2.jpg'},
  {id: 130, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e3.jpg'},
  {id: 131, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e4.jpg'},
  {id: 132, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e5.jpg'},
  {id: 133, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e6.jpg'},
  {id: 134, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e7.jpg'},
  {id: 135, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e8.jpg'},
  {id: 136, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e9.jpg'},
  {id: 137, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e10.jpg'},
  {id: 138, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e11.jpg'},
  {id: 139, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e12.jpg'},
  {id: 140, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e13.jpg'},
  {id: 141, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e14.jpg'},
  {id: 142, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e15.jpg'},
  {id: 143, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e16.jpg'},
  {id: 144, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e17.jpg'},
  {id: 145, category: 'bremen', caption: 'Bremen Okt. 2012', url: 'assets/my_images/e18.jpg'},

  {id: 146, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f1.jpg'},
  {id: 147, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f2.jpg'},
  {id: 148, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f3.jpg'},
  {id: 149, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f4.jpg'},
  {id: 150, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f5.jpg'},
  {id: 151, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f6.jpg'},
  {id: 152, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f7.jpg'},
  {id: 153, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f8.jpg'},
  {id: 154, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f9.jpg'},
  {id: 155, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f10.jpg'},
  {id: 156, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f11.jpg'},
  {id: 157, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f12.jpg'},
  {id: 158, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f13.jpg'},
  {id: 159, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f14.jpg'},
  {id: 160, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f15.jpg'},
  {id: 161, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f16.jpg'},
  {id: 162, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f17.jpg'},
  {id: 163, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f18.jpg'},
  {id: 164, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f19.jpg'},
  {id: 165, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f20.jpg'},
  {id: 166, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f21.jpg'},
  {id: 167, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f22.jpg'},
  {id: 168, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f23.jpg'},
  {id: 169, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f24.jpg'},
  {id: 170, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f25.jpg'},
  {id: 171, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f26.jpg'},
  {id: 172, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f27.jpg'},
  {id: 173, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f28.jpg'},
  {id: 174, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f29.jpg'},
  {id: 175, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f30.jpg'},
  {id: 176, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f31.jpg'},
  {id: 177, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f31.jpg'},
  {id: 178, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f32.jpg'},
  {id: 179, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f33.jpg'},
  {id: 180, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f34.jpg'},
  {id: 181, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f35.jpg'},
  {id: 182, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f36.jpg'},
  {id: 183, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f37.jpg'},
  {id: 184, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f38.jpg'},
  {id: 185, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f39.jpg'},
  {id: 186, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f40.jpg'},
  {id: 187, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f41.jpg'},
  {id: 188, category: 'karlsruhe', caption: 'Karlsruhe Sept. 2012', url: 'assets/my_images/f42.jpg'},

  // marseille
  {id: 189, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g1.jpg'},
  {id: 190, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g2.jpg'},
  {id: 191, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g3.jpg'},
  {id: 192, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g4.jpg'},
  {id: 193, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g5.jpg'},
  {id: 194, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g6.jpg'},
  {id: 195, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g7.jpg'},
  {id: 196, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g8.jpg'},
  {id: 197, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g9.jpg'},
  {id: 198, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g10.jpg'},
  {id: 199, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g11.jpg'},
  {id: 200, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g12.jpg'},
  {id: 201, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g13.jpg'},
  {id: 202, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g14.jpg'},
  {id: 203, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g15.jpg'},
  {id: 204, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g16.jpg'},
  {id: 205, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g17.jpg'},
  {id: 206, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g18.jpg'},
  {id: 207, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g19.jpg'},
  {id: 208, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g20.jpg'},
  {id: 209, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g21.jpg'},
  {id: 210, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g22.jpg'},
  {id: 211, category: 'marseille', caption: 'Marseille März 2013', url: 'assets/my_images/g23.jpg'},

];

@Injectable({
  providedIn: 'root'
})
export class ImageService {

  visibleImages = [];

  getImages() {
    return this.visibleImages = IMAGES.slice(0);
  }

  getImage(id: number) {
    return IMAGES.slice(0).find(image => image.id === id);
  }
}


